import { Dimensions, StyleSheet } from "react-native";

import { theme } from "../../../../theme";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const PROFILE_DRAWER_WIDTH = SCREEN_WIDTH * 0.88;

export const profileDetailStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "rgba(15, 23, 42, 0.52)",
  },
  backdrop: {
    flex: 1,
  },
  drawerContainer: {
    width: PROFILE_DRAWER_WIDTH,
    height: "100%",
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 28,
    borderBottomLeftRadius: 28,
    overflow: "hidden",
    ...theme.shadows.elevation1,
  },
  header: {
    minHeight: 74,
    paddingBottom: 10,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderAlpha.faint,
  },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surfaceSoft,
  },
  logoutHeaderButton: {
    backgroundColor: theme.colors.semantic.danger.bg,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: theme.colors.textTitle,
    letterSpacing: -0.2,
  },
  headerSubtitle: {
    marginTop: 1,
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textBody,
  },
  profileHero: {
    alignItems: "center",
    paddingTop: 24,
    paddingBottom: 20,
    paddingHorizontal: 24,
    backgroundColor: theme.colors.surface,
    overflow: "hidden",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  heroGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    top: -100,
    backgroundColor: theme.colors.semantic.success.bg,
  },
  avatarWrapper: {
    position: "relative",
    marginBottom: 12,
  },
  avatarRing: {
    width: 104,
    height: 104,
    borderRadius: 52,
    padding: 4,
    backgroundColor: theme.colors.semantic.success.bg,
    borderWidth: 1,
    borderColor: "rgba(31, 92, 77, 0.15)",
    ...theme.shadows.elevation1,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 48,
  },
  avatarPlaceholder: {
    flex: 1,
    borderRadius: 48,
    backgroundColor: theme.colors.surfaceSoft,
    justifyContent: "center",
    alignItems: "center",
  },
  uploadingOverlay: {
    ...StyleSheet.absoluteFill,
    borderRadius: 52,
    backgroundColor: "rgba(15, 23, 42, 0.68)",
    justifyContent: "center",
    alignItems: "center",
  },
  uploadingText: {
    marginTop: 6,
    fontSize: 10,
    fontWeight: "700",
    color: theme.colors.surface,
  },
  photoActionBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: theme.colors.surface,
    ...theme.shadows.buttonGlow,
  },
  photoAddBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: theme.colors.brand,
  },
  photoEditBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.brand,
  },
  profileName: {
    maxWidth: "90%",
    fontSize: 22,
    fontWeight: "800",
    color: theme.colors.textTitle,
    letterSpacing: -0.5,
  },
  profileEmail: {
    maxWidth: "90%",
    marginTop: 4,
    fontSize: 13,
    fontWeight: "500",
    color: theme.colors.textBody,
  },
  profileMeta: {
    marginTop: 12,
  },
  accountBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 100,
    backgroundColor: theme.colors.semantic.success.bg,
  },
  accountBadgeDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginRight: 7,
    backgroundColor: theme.colors.brand,
  },
  accountBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.brand,
  },
  photoActionHint: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 9,
  },
  photoHint: {
    marginLeft: 4,
    fontSize: 10,
    fontWeight: "500",
    color: theme.colors.textBody,
  },
  tabContainer: {
    flexDirection: "row",
    marginHorizontal: 12,
    marginTop: 14,
    padding: 4,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.045)",
  },
  tabButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    minWidth: 0,
    position: "relative",
  },
  tabButtonActive: {
    backgroundColor: theme.colors.surface,
    ...theme.shadows.elevation1,
  },
  tabIconContainer: {
    width: 26,
    height: 26,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  tabIconContainerActive: {
    backgroundColor: theme.colors.semantic.success.bg,
  },
  tabText: {
    marginLeft: 4,
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textBody,
    flexShrink: 1,
    includeFontPadding: false,
  },
  tabTextActive: {
    color: theme.colors.brand,
    fontWeight: "800",
  },
  contentContainer: {
    flex: 1,
  },
  profileScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
  },
  cardSectionTitle: {
    marginTop: 24,
    marginBottom: 10,
    fontSize: 14,
    fontWeight: "800",
    color: theme.colors.textTitle,
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: theme.colors.semantic.success.bg,
  },
  editButtonText: {
    marginLeft: 5,
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.brand,
  },
  infoCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: theme.colors.borderAlpha.subtle,
    ...theme.shadows.elevation1,
  },
  infoRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
  },
  infoIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textBody,
    marginBottom: 3,
  },
  infoValue: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "700",
    color: theme.colors.textTitle,
  },
  infoDivider: {
    height: 1,
    marginLeft: 52,
    backgroundColor: theme.colors.borderAlpha.faint,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 60,
  },
  loadingIcon: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    backgroundColor: theme.colors.semantic.success.bg,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 13,
    fontWeight: "600",
    color: theme.colors.textBody,
  },
});
