import { StyleSheet } from "react-native";

import { theme } from "../../../theme/colors";

export const occurrenceCardStyles = StyleSheet.create({
  card: {
    overflow: "hidden",
    marginBottom: 18,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    borderColor: theme.colors.inputBg,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.elevation1,
  },
  postHeader: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  postHeaderMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  contentPressed: {
    opacity: 0.84,
  },
  authorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.brand,
  },
  authorAvatarImage: {
    width: "100%",
    height: "100%",
  },
  authorInitials: {
    color: theme.colors.surface,
    fontSize: 13,
    fontWeight: "900",
  },
  authorContent: {
    flex: 1,
    minWidth: 0,
    marginLeft: 11,
  },
  authorName: {
    color: theme.colors.textTitle,
    fontSize: 13,
    fontWeight: "900",
  },
  authorMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 5,
  },
  statusBadge: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 8,
    borderRadius: theme.radius.button,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusText: {
    fontSize: 9,
    fontWeight: "900",
  },
  urgentBadge: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    borderRadius: theme.radius.button,
    backgroundColor: theme.colors.semantic.danger.bg,
  },
  urgentText: {
    color: theme.colors.semantic.danger.text,
    fontSize: 9,
    fontWeight: "800",
  },
  moreOptionsButton: {
    width: 38,
    height: 38,
    marginLeft: 6,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  imageContainer: {
    height: 215,
    backgroundColor: theme.colors.inputBg,
  },
  imagePressed: {
    opacity: 0.94,
  },
  image: {
    width: "100%",
    height: "100%",
  },
  imageFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.inputBg,
  },
  imageFallbackText: {
    color: theme.colors.textBody,
    fontSize: 11,
    fontWeight: "600",
  },
  actionsRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 11,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.inputBg,
  },
  actionsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  actionIconButton: {
    width: 34,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  forceButton: {
    minWidth: 68,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 11,
    borderRadius: 22,
    backgroundColor: "transparent",
  },
  forceButtonActive: {
    backgroundColor: theme.colors.semantic.success.bg,
  },
  forceButtonLoading: {
    opacity: 0.52,
  },
  forceButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  echoIcon: {
    width: 29,
    height: 29,
  },
  echoCount: {
    minWidth: 13,
    color: theme.colors.textBody,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  echoCountActive: {
    color: theme.colors.action,
  },
  commentsCount: {
    flexShrink: 1,
    color: theme.colors.textBody,
    fontSize: 9,
    fontWeight: "600",
    textAlign: "right",
  },
  captionContainer: {
    paddingHorizontal: 13,
    paddingTop: 11,
    paddingBottom: 12,
  },
  captionText: {
    color: theme.colors.textTitle,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  postMetaRow: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 7,
  },
  postMetaLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
    gap: 4,
  },
  postMetaText: {
    color: theme.colors.textBody,
    fontSize: 9,
    fontWeight: "600",
  },
  metaDot: {
    width: 3,
    height: 3,
    marginHorizontal: 2,
    borderRadius: 2,
    backgroundColor: theme.colors.textBody,
  },
  moreButton: {
    minHeight: 30,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  moreText: {
    color: theme.colors.brand,
    fontSize: 11,
    fontWeight: "900",
  },
});
