import { StyleSheet } from "react-native";

import { theme } from "../../../../theme/colors";

export const petFormStyles = StyleSheet.create({
    modalBackdrop: {
        flex: 1,
        justifyContent: "flex-end",
        backgroundColor: "rgba(15,23,42,0.56)",
    },
    modalContainer: {
        maxHeight: "88%",
        padding: 20,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        backgroundColor: theme.colors.surface,
    },
    modalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: theme.colors.textTitle,
    },
    modalSubtitle: {
        marginTop: 3,
        fontSize: 12,
        color: theme.colors.textBody,
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.colors.surfaceSoft,
    },
    photoSelector: {
        width: 116,
        height: 116,
        alignSelf: "center",
        marginBottom: 22,
        borderRadius: 58,
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
        borderWidth: 2,
        borderColor: theme.colors.semantic.success.bg,
        backgroundColor: theme.colors.surfaceSoft,
    },
    selectedPhoto: {
        width: "100%",
        height: "100%",
    },
    photoTitle: {
        marginTop: 5,
        fontSize: 11,
        fontWeight: "700",
        color: theme.colors.brand,
    },
    photoHint: {
        marginTop: 2,
        fontSize: 9,
        color: theme.colors.textBody,
    },
    label: {
        marginTop: 15,
        marginBottom: 7,
        fontSize: 12,
        fontWeight: "700",
        color: theme.colors.textTitle,
    },
    inputContainer: {
        minHeight: 52,
        paddingHorizontal: 14,
        borderRadius: 14,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderColor: theme.colors.inputBg,
        backgroundColor: theme.colors.surfaceSoft,
    },
    input: {
        flex: 1,
        marginLeft: 10,
        fontSize: 14,
        color: theme.colors.textTitle,
    },
    optionContainer: {
        flexDirection: "row",
        gap: 8,
    },
    optionButton: {
        flex: 1,
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 7,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.inputBg,
        backgroundColor: theme.colors.surfaceSoft,
    },
    sizeButton: {
        flex: 1,
        minHeight: 44,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.inputBg,
        backgroundColor: theme.colors.surfaceSoft,
    },
    optionButtonActive: {
        borderColor: theme.colors.brand,
        backgroundColor: theme.colors.brand,
    },
    optionText: {
        fontSize: 12,
        fontWeight: "700",
        color: theme.colors.textBody,
    },
    optionTextActive: {
        color: theme.colors.surface,
    },
    saveButton: {
        minHeight: 54,
        marginTop: 26,
        marginBottom: 20,
        borderRadius: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        backgroundColor: theme.colors.brand,
        ...theme.shadows.buttonGlow,
    },
    saveButtonDisabled: {
        opacity: 0.6,
    },
    saveButtonText: {
        fontSize: 14,
        fontWeight: "800",
        color: theme.colors.surface,
    },
});
