"""completar_modelos_der

Revision ID: 6ec9a90cf3ac
Revises: None
Create Date: 2026-08-04 19:53:45.818662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6ec9a90cf3ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('tipo_conta', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('localizacao_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('localizacao_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('localizacao', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_conta')
    )
    op.create_index(op.f('ix_contas_email'), 'contas', ['email'], unique=True)
    op.create_index(op.f('ix_contas_id_conta'), 'contas', ['id_conta'], unique=False)
    op.create_table('mensagens_chat',
    sa.Column('id_mensagem', sa.Integer(), nullable=False),
    sa.Column('id_remetente_conta', sa.Integer(), nullable=False),
    sa.Column('id_destinatario_conta', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_destinatario_conta'], ['contas.id_conta'], ),
    sa.ForeignKeyConstraint(['id_remetente_conta'], ['contas.id_conta'], ),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    op.create_index(op.f('ix_mensagens_chat_id_mensagem'), 'mensagens_chat', ['id_mensagem'], unique=False)
    op.create_table('ocorrencias',
    sa.Column('id_ocorrencia', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('tipo_ocorrencia', sa.String(length=50), nullable=False),
    sa.Column('status_badge', sa.String(length=20), nullable=False),
    sa.Column('tipo_animal', sa.String(length=50), nullable=False),
    sa.Column('raca', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('porte', sa.String(length=20), nullable=True),
    sa.Column('idade', sa.String(length=20), nullable=True),
    sa.Column('saude_critica', sa.Boolean(), nullable=False),
    sa.Column('saude_detalhes', sa.Text(), nullable=True),
    sa.Column('cuidados_iniciais', sa.Text(), nullable=True),
    sa.Column('deficiencia', sa.Boolean(), nullable=False),
    sa.Column('deficiencia_detalhes', sa.Text(), nullable=True),
    sa.Column('nivel_urgencia', sa.String(length=20), nullable=False),
    sa.Column('data_ocorrencia', sa.DateTime(), nullable=False),
    sa.Column('endereco_localizacao', sa.String(length=500), nullable=True),
    sa.Column('localizacao', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.PrimaryKeyConstraint('id_ocorrencia')
    )
    op.create_index(op.f('ix_ocorrencias_id_ocorrencia'), 'ocorrencias', ['id_ocorrencia'], unique=False)
    op.create_table('ongs',
    sa.Column('id_ong', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('endereco_completo', sa.String(length=500), nullable=False),
    sa.Column('nome_gestor', sa.String(length=255), nullable=False),
    sa.Column('cpf_gestor', sa.String(length=14), nullable=False),
    sa.Column('comprovante_url', sa.String(length=500), nullable=True),
    sa.Column('selo_verificado', sa.Boolean(), nullable=False),
    sa.Column('oferece_lar_temporario', sa.Boolean(), nullable=False),
    sa.Column('vagas_emergenciais', sa.Boolean(), nullable=False),
    sa.Column('capacidade_total', sa.Integer(), nullable=True),
    sa.Column('lotacao_atual', sa.Integer(), nullable=True),
    sa.Column('link_prestacao_contas', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.PrimaryKeyConstraint('id_ong'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('id_conta')
    )
    op.create_index(op.f('ix_ongs_id_ong'), 'ongs', ['id_ong'], unique=False)
    op.create_table('usuarios_fisicos',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('tem_pet', sa.Boolean(), nullable=False),
    sa.Column('social_login_id', sa.String(length=255), nullable=True),
    sa.Column('raio_pesquisa_km', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('id_conta')
    )
    op.create_index(op.f('ix_usuarios_fisicos_id_usuario'), 'usuarios_fisicos', ['id_usuario'], unique=False)
    op.create_table('avistamentos',
    sa.Column('id_avistamento', sa.Integer(), nullable=False),
    sa.Column('id_ocorrencia', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('eh_de_raca', sa.Boolean(), nullable=False),
    sa.Column('raca', sa.String(length=100), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('localizacao', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.ForeignKeyConstraint(['id_ocorrencia'], ['ocorrencias.id_ocorrencia'], ),
    sa.PrimaryKeyConstraint('id_avistamento')
    )
    op.create_index(op.f('ix_avistamentos_id_avistamento'), 'avistamentos', ['id_avistamento'], unique=False)
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('id_ocorrencia', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.ForeignKeyConstraint(['id_ocorrencia'], ['ocorrencias.id_ocorrencia'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_index(op.f('ix_comentarios_id_comentario'), 'comentarios', ['id_comentario'], unique=False)
    op.create_table('denuncias',
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('id_ocorrencia', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.ForeignKeyConstraint(['id_ocorrencia'], ['ocorrencias.id_ocorrencia'], ),
    sa.PrimaryKeyConstraint('id_denuncia')
    )
    op.create_index(op.f('ix_denuncias_id_denuncia'), 'denuncias', ['id_denuncia'], unique=False)
    op.create_table('interacoes',
    sa.Column('id_interacao', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('id_ocorrencia', sa.Integer(), nullable=False),
    sa.Column('tipo_interacao', sa.String(length=20), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.ForeignKeyConstraint(['id_ocorrencia'], ['ocorrencias.id_ocorrencia'], ),
    sa.PrimaryKeyConstraint('id_interacao')
    )
    op.create_index(op.f('ix_interacoes_id_interacao'), 'interacoes', ['id_interacao'], unique=False)
    op.create_table('pets',
    sa.Column('id_pet', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raca', sa.String(length=100), nullable=True),
    sa.Column('porte', sa.String(length=20), nullable=True),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios_fisicos.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pet')
    )
    op.create_index(op.f('ix_pets_id_pet'), 'pets', ['id_pet'], unique=False)
    op.create_table('projetos_adocao',
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('id_ong', sa.Integer(), nullable=False),
    sa.Column('tipo_conteudo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_ong'], ['ongs.id_ong'], ),
    sa.PrimaryKeyConstraint('id_projeto')
    )
    op.create_index(op.f('ix_projetos_adocao_id_projeto'), 'projetos_adocao', ['id_projeto'], unique=False)
    op.create_table('voluntariados_seguidores',
    sa.Column('id_relacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_ong', sa.Integer(), nullable=False),
    sa.Column('tipo_relacao', sa.String(length=20), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('status_aprovacao', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_ong'], ['ongs.id_ong'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios_fisicos.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_relacao')
    )
    op.create_index(op.f('ix_voluntariados_seguidores_id_relacao'), 'voluntariados_seguidores', ['id_relacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voluntariados_seguidores_id_relacao'), table_name='voluntariados_seguidores')
    op.drop_table('voluntariados_seguidores')
    op.drop_index(op.f('ix_projetos_adocao_id_projeto'), table_name='projetos_adocao')
    op.drop_table('projetos_adocao')
    op.drop_index(op.f('ix_pets_id_pet'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_interacoes_id_interacao'), table_name='interacoes')
    op.drop_table('interacoes')
    op.drop_index(op.f('ix_denuncias_id_denuncia'), table_name='denuncias')
    op.drop_table('denuncias')
    op.drop_index(op.f('ix_comentarios_id_comentario'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_avistamentos_id_avistamento'), table_name='avistamentos')
    op.drop_table('avistamentos')
    op.drop_index(op.f('ix_usuarios_fisicos_id_usuario'), table_name='usuarios_fisicos')
    op.drop_table('usuarios_fisicos')
    op.drop_index(op.f('ix_ongs_id_ong'), table_name='ongs')
    op.drop_table('ongs')
    op.drop_index(op.f('ix_ocorrencias_id_ocorrencia'), table_name='ocorrencias')
    op.drop_table('ocorrencias')
    op.drop_index(op.f('ix_mensagens_chat_id_mensagem'), table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    op.drop_index(op.f('ix_contas_id_conta'), table_name='contas')
    op.drop_index(op.f('ix_contas_email'), table_name='contas')
    op.drop_table('contas')
    # ### end Alembic commands ###