"""add_auth_verification_fields

Revision ID: be3d516310b6
Revises: '6ec9a90cf3ac'
Create Date: 2026-08-06 19:14:07.663789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'be3d516310b6'
down_revision: Union[str, None] = '6ec9a90cf3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('email_confirmado', sa.Boolean(), nullable=False))
    op.add_column('contas', sa.Column('codigo_confirmacao', sa.String(length=6), nullable=True))
    op.add_column('contas', sa.Column('codigo_recuperacao', sa.String(length=6), nullable=True))
    op.add_column('contas', sa.Column('codigo_recuperacao_expira', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas', 'codigo_recuperacao_expira')
    op.drop_column('contas', 'codigo_recuperacao')
    op.drop_column('contas', 'codigo_confirmacao')
    op.drop_column('contas', 'email_confirmado')
    # ### end Alembic commands ###