import { StyleSheet } from "react-native";

import { theme } from "../../../../theme/colors";

export const profileAccountStyles = StyleSheet.create({
  accountCard: {
    flexDirection: "row",
    marginTop: 24,
    padding: 16,
    borderRadius: 18,
    backgroundColor: theme.colors.semantic.success.bg,
    borderWidth: 1,
    borderColor: theme.colors.brandAlpha.soft,
  },
  accountIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surface,
  },
  accountContent: {
    flex: 1,
    marginLeft: 12,
  },
  accountTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: theme.colors.brand,
  },
  accountDescription: {
    marginTop: 3,
    fontSize: 11,
    lineHeight: 16,
    color: theme.colors.textBody,
  },
  manageAccountLabel: {
    marginTop: 24,
    marginBottom: 10,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    color: theme.colors.textBody,
  },
  deleteAccountCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.semantic.danger.bg,
    ...theme.shadows.elevation1,
  },
  deleteAccountHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  deleteAccountIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.semantic.danger.bg,
  },
  deleteAccountContent: {
    flex: 1,
    marginLeft: 12,
  },
  deleteAccountTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: theme.colors.textTitle,
  },
  deleteAccountDescription: {
    marginTop: 3,
    fontSize: 11,
    lineHeight: 16,
    color: theme.colors.textBody,
  },
  deleteAccountButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
    borderRadius: 14,
    backgroundColor: theme.colors.semantic.danger.bg,
    borderWidth: 1,
    borderColor: theme.colors.semantic.danger.text,
  },
  deleteAccountButtonText: {
    marginLeft: 7,
    fontSize: 13,
    fontWeight: "800",
    color: theme.colors.semantic.danger.text,
  },
  deleteModalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    backgroundColor: "rgba(15, 23, 42, 0.62)",
  },
  deleteModalBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  deleteModalCard: {
    width: "100%",
    maxWidth: 420,
    padding: 22,
    borderRadius: 22,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.elevation1,
  },
  deleteModalIcon: {
    width: 52,
    height: 52,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.semantic.danger.bg,
  },
  deleteModalTitle: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: "800",
    color: theme.colors.textTitle,
  },
  deleteModalDescription: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    color: theme.colors.textBody,
  },
  deletePasswordLabel: {
    marginTop: 20,
    marginBottom: 8,
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.textTitle,
  },
  deletePasswordWrapper: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.semantic.danger.bg,
    backgroundColor: theme.colors.surface,
  },
  deletePasswordInput: {
    flex: 1,
    marginLeft: 10,
    paddingVertical: 0,
    fontSize: 14,
    color: theme.colors.textTitle,
  },
  deletePasswordToggle: {
    width: 48,
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteModalActions: {
    marginTop: 20,
    gap: 10,
  },
  deleteModalCancelButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.semantic.danger.bg,
  },
  deleteModalCancelText: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.colors.textBody,
  },
  deleteModalConfirmButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: theme.colors.semantic.danger.text,
  },
  deleteModalButtonDisabled: {
    opacity: 0.7,
  },
  deleteModalConfirmText: {
    marginLeft: 7,
    fontSize: 13,
    fontWeight: "800",
    color: theme.colors.surface,
  },
});
